### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by davecastlevania** [jadeheart/prj-rev-bwfs-dasmoto#4]
Great job with this project. I can tell that you worked really hard on it. You were able to make everything look exactly to spec and it shows that you are getting a real good understanding of how to blend HTML and CSS together. There aren't much improvements I would suggest but as a challenge I would try coming back to this project later after you learn a little more about responsive design and media queries so that you can make this into a mobile site. Nicely done, pat yourself on the back for a job well done.

**Comment by jadeheart** [comment]
Thanks for your input. It is much appreciated.
